language: php
php:
  - '7.0'
  - '7.1'
  - hhvm # on Trusty only
  - nightly

matrix:
  allow_failures:
    - php: hhvm

mysql:
  database: phackptest
  username: root
  encoding: utf8

install:
  - composer install

script: phpunit --bootstrap vendor/autoload.php --configuration phpunit.xml tests