language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - hhvm # on Trusty only
  - nightly

matrix:
  allow_failures:
    - php: hhvm

services:
  - mysql

mysql:
  database: phackptest
  username: root
  encoding: utf8

before_install:
  - mysql -e 'CREATE DATABASE phackptest;'

install:
  - composer install

script: 
  php -S localhost:7000 -t tests/src/ & phpunit --bootstrap vendor/autoload.php --configuration phpunit.xml tests
